name = "Inheritance"
author = "Artea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b8b8d7a1fd5ca516cfc91cc221d7ebb58784c92c66a0b0ded98ece55b586d6e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
