name = "Inheritance"
author = "Artea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eebb3467a2a8bf945d79b258235db47a066e522ed6be0b9237e5cbc2bb559c04"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
